project_id = "msnakgazemgwnxzgfiio"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.generate-content]
verify_jwt = false