-- NOOP migration retained for history alignment
-- This file corresponds to a remote baseline that already exists on the database.
-- Intentionally left blank to avoid re-applying CREATE statements that would fail when objects already exist.
