name: E2E Live (Manual)

on:
  workflow_dispatch:
    inputs:
      suite:
        description: "Chọn bộ live tests để chạy"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - orchestrator3000
          - generate-content
          - gemini
          - serpapi

concurrency:
  group: e2e-live
  cancel-in-progress: true

jobs:
  e2e-live:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers & deps
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      - name: Run Playwright Live Tests
        env:
          CI: '1'
          VITE_USE_MOCK_CONTENT: 'false'
          VITE_BYPASS_AUTH: 'true'
          VITE_E2E_TEST_MODE: 'true'
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          SUITE="${{ github.event.inputs.suite }}"
          if [ "$SUITE" = "orchestrator3000" ]; then
            PATTERN="tests/e2e/generate-3000-ui-live.spec.ts"
          elif [ "$SUITE" = "generate-content" ]; then
            PATTERN="tests/e2e/generate-content-live.spec.ts"
          elif [ "$SUITE" = "gemini" ]; then
            PATTERN="tests/e2e/generate-content-gemini-live.spec.ts"
          elif [ "$SUITE" = "serpapi" ]; then
            PATTERN="tests/e2e/serpapi-live.spec.ts"
          else
            PATTERN="tests/e2e/*live.spec.ts"
          fi
          echo "Running suite: $SUITE with pattern: $PATTERN"
          npx playwright test -c playwright.live.config.ts "$PATTERN" --reporter=github --workers=1

      - name: Upload test artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore
