name: E2E Nightly (Mock)

on:
  schedule:
    - cron: "0 18 * * *" # chạy hằng ngày 01:00 VN (18:00 UTC)
  workflow_dispatch:

concurrency:
  group: e2e-nightly
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers & deps
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      - name: Run Playwright E2E (mock mode)
        env:
          CI: '1'
        run: |
          npm run -s test:e2e -- --reporter=github --workers=2

      - name: Upload test artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore
